import test  from '@playwright/test';
test("Create Test Lead",async({page})=>{
await page.goto("http://leaftaps.com/opentaps/control/main")
    await page.locator("#username").fill("Demosalesmanager")
    await page.locator("#password").fill("crmsfa")
    await page.locator(".decorativeSubmit").click()
    await page.waitForTimeout(2000)
    await page.locator(`text='CRM/SFA'`).click()
    await page.waitForTimeout(2000)
    await page.locator(`text='Leads'`).click()
    await page.waitForTimeout(1000)
    await page.locator(`text='Create Lead'`).first().click()
    await page.waitForTimeout(1000)
    await page.locator("#createLeadForm_companyName").fill("Test Company")
    await page.locator("#createLeadForm_firstName").fill("Anjani")
    await page.locator("#createLeadForm_lastName").fill("Priya")
    await page.locator("#createLeadForm_personalTitle").fill("Ms")
    await page.locator("#createLeadForm_generalProfTitle").fill("Test")
    await page.locator("#createLeadForm_annualRevenue").fill("50000")
    await page.locator("#createLeadForm_departmentName").fill("Test Department")
    await page.locator("#createLeadForm_primaryPhoneNumber").fill("123-194-789")
    await page.waitForTimeout(2000)
    await page.locator(".smallSubmit").click()
     await page.waitForTimeout(2000)
})