import test,{expect} from '@playwright/test'

test("Assignment using locators",async({page})=>{    
    await page.goto("http://leaftaps.com/opentaps/control/main")
    await page.locator("//input[@id='username']").fill("Demosalesmanager")
    await page.locator("//input[@id='password']").fill("crmsfa")
    await page.locator("//input[@class='decorativeSubmit']").click()
    await page.locator("//a[contains(text(),'CRM')]").click()
    await page.locator("//a[contains(text(),'Leads')]").click()
    await page.locator("//a[contains(text(),'Create Lead')]").click()
    await page.locator("//input[@id='createLeadForm_companyName']").fill("Test Company")
    await page.locator("//input[@id='createLeadForm_firstName']").fill("Anjani")
    await page.locator("//input[@id='createLeadForm_lastName']").fill("Priya")
    await page.locator("//input[@id='createLeadForm_personalTitle']").fill("Ms")
    await page.locator("//input[@id='createLeadForm_generalProfTitle']").fill("Test")
    await page.locator("//input[@id='createLeadForm_annualRevenue']").fill("50000")
    await page.locator("//input[@id='createLeadForm_departmentName']").fill("Test Department")
    await page.locator("//input[@id='createLeadForm_primaryPhoneNumber']").fill("123-194-789")
    await page.locator("//input[@class='smallSubmit']").click()
    await page.waitForTimeout(2000)
    const compname=page.locator("//span[@id='viewLead_companyName_sp']")
    const firstname=page.locator("//span[@id='viewLead_firstName_sp']")
    const lastname=page.locator("//span[@id='viewLead_lastName_sp']")
    const status=page.locator("//span[@id='viewLead_statusId_sp']")
    await expect.soft(compname).toContainText("Test Company")
     await expect.soft(firstname).toContainText("Anjani")
     await expect.soft(lastname).toContainText("Priya")
     await expect.soft(status).toContainText("Assigned")
    console.log(await page.title())

})

test("Edit Test Lead",async({page})=>{ 
    await page.goto("http://leaftaps.com/opentaps/control/main")
    await page.locator("//input[@id='username']").fill("Demosalesmanager")
    await page.locator("//input[@id='password']").fill("crmsfa")
    await page.locator("//input[@class='decorativeSubmit']").click()
    await page.locator("//a[contains(text(),'CRM')]").click()
    await page.locator("//a[contains(text(),'Leads')]").click()
    await page.locator("//a[text()='Find Leads']").click()
    await page.getByText('first name').nth(2).fill("Anjani")
    await page.locator("//button[text()='Find Leads']").click()
    await page.getByRole("link",{name:"Anjani"}).first().click()
    await page.getByRole("link",{name:"Edit"}).click()
    await page.locator("//input[@id='updateLeadForm_companyName']").fill("New Test Company")
    await page.locator("//input[@id='updateLeadForm_annualRevenue']").fill("60000")
    await page.locator("//input[@id='updateLeadForm_departmentName']").fill("Test Department")
    await page.locator("//input[@name='submitButton']").first().click()
     const compname=page.locator("//span[@id='viewLead_companyName_sp']")
     await expect.soft(compname).toContainText("New Test Company")
  })

  test.only("Create a new Account ",async({page})=>{ 
    await page.goto("https://login.salesforce.com/")
    await page.getByLabel('username').fill("dilipkumar.rajendran@testleaf.com")
    await page.getByLabel('password').fill('TestLeaf@2025')
    await page.locator("//input[@id='Login']").click()
    await page.waitForTimeout(5000)
    const title= await page.title()
    console.log("Page title is: "+title)
    console.log("URL of page: "+ page.url())
    expect.soft(title).toContain('Home | Salesforce')
    expect(page.url()).toContain('https://testleaf.lightning.force.com/lightning/page/home')
    await page.locator(".slds-icon-waffle").click()
    await page.getByLabel("View All Applications").click()
    await page.waitForTimeout(3000)
    await page.getByPlaceholder("Search apps or items...").fill("service")
    await page.locator("(//span//p)[1]").click()
    await page.locator("//span[text()='Accounts']").click()
    page.getByRole("button",{name:"New"}).click()
     await page.waitForTimeout(3000)
    await page.locator(".slds-input").nth(3).fill("Testnameaccount")
    await page.getByRole("button",{name:"SaveEdit"}).click()
    console.log("Account created successfully")
  })
